### ISSUE TITLE
Cannot access Planar Ally using docker-compose and traefik method

### ISSUE THREAD

**Issue by MaxBurn7** [Kruptein/planarally-docs#81]
I modeled my compose file after the [example ](https://www.planarally.io/server/setup/self-hosting/#docker-container-with-docker-compose-and-traefik) given.

```
planarally:
    image: kruptein/planarally:latest
    container_name: planarally
    restart: unless-stopped
    networks:
      - traefik_network
    volumes:
      - /mnt/planarally/data:/planarally/data/
      - /mnt/planarally/static/assets:/planarally/static/assets/
    labels:
      - traefik.http.services.pa.loadbalancer.server.scheme=https
      - traefik.http.services.pa.loadbalancer.server.port=8000
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.pa-http.service=pa
      - traefik.http.routers.pa-http.rule=Host(`pa.domain.tdl`)
      - traefik.http.routers.pa-http.entrypoints=web
      - traefik.http.routers.pa.service=pa
      - traefik.http.routers.pa.rule=Host(`pa.domain.tdl`)
      - traefik.http.routers.pa.entrypoints=websecure
      - traefik.http.routers.pa.tls=true
      - traefik.http.routers.pa.tls.certresolver=cloudflare
      - traefik.http.routers.pa.tls.domains[0].main=domain.tdl
      - traefik.http.routers.pa.tls.domains[0].sans=*domain.tdl
      - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
      # these are required, this forces the websocket to forward over https
      - traefik.http.routers.pa.middlewares=ssl-header
      - traefik.http.middlewares.ssl-header.headers.customrequestheaders.X-Forwarded-Proto=https
```

Looking at the Traefik dashboard it says it is running, but I get a time out when I go to "pa.domain.tdl" (which doesn't happen when I go to whoami.domain.tdl, the sample service in the traefik tutorial).

Any suggestions on where to look at what I might have done wrong?

For more context I am running Traefik: v2.4
